// Generated by Wrangler on Thu Aug 01 2024 20:18:42 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
