name = "cloudflare"
compatibility_date = "2024-08-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "bookmarqly-db"
database_id = "9a14c1b3-6364-49dc-b45a-496406d4e71f"