import "@repo/ui/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Providers from "@/components/Providers"
import Header from "@/components/header/Header"
import Sidebar from "@/components/sidebar/Sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="flex w-full">
            <Sidebar />
            <div className=" w-full">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
