import "@repo/ui/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Providers from "@/components/Providers"
import Header from "@/components/header/Header"
import Sidebar from "@/components/sidebar/Sidebar"
import AppHeader from "@/components/header/AppHeader"
import MainLayout from "@/components/layout/MainLayout"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {/* <MainLayout>{children}</MainLayout> */}
          <div className="flex w-full h-screen">
            <Sidebar />
            <div className="flex-1">
              <AppHeader />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
