// Generated by Wrangler on Sun Aug 04 2024 08:32:50 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  AUTH_SECRET: "f8vYfLTlhP0fpeTmgpNshx7jD4PI7fwTIj4nCLAUOwc="
  DB: D1Database
}
