name = "bookmarqly-db"
main = "src/index.ts"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "bookmarqly-db"
database_id = "9a14c1b3-6364-49dc-b45a-496406d4e71f"

[vars]
binding = "JWT_SECRET"
AUTH_SECRET = "f8vYfLTlhP0fpeTmgpNshx7jD4PI7fwTIj4nCLAUOwc="

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"